# This is quick pandas recup!Fell free to use!

First import!

In [1]:
import pandas as pd
import numpy as np

## 1.Read data

Than we need to read and inspect our titanic data set and check data types

Data set used: https://www.kaggle.com/datasets/heptapod/titanic?resource=download

In [2]:
data_path = r"data\train_and_test2.csv" # we can write data path for our convinienve

U can additionally use other formatsd based on your data like excel, json, parquet, etc. For example, to read an Excel file, you can use the following code:

```python
pd.read_excel('file.xlsx', sheet_name='Sheet1')
pd.read_json('file.json')
pd.read_parquet('file.parquet')  
pd.read_sql('SELECT * FROM table', con=engine)
```

In [3]:
df_raw = pd.read_csv(
    data_path,
    sep=',', #we use sep to specify the delimiter used in the CSV file
    encoding = 'utf-8', #we need UTF-8 encoding to read the file correctly
    nrows=100, #use nrow to limit the number of rows read from the file
    na_values = ["NA", "na", "N/A", "n/a", "null", "NULL", ""] #just in case there are other representations of missing values in the dataset
)

Lets check

In [4]:
df_raw

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
96,97,71.0,34.6542,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
97,98,23.0,63.3583,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
98,99,34.0,23.0000,1,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
99,100,34.0,26.0000,0,1,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0

Lets keep usefull columns and rename

In [5]:
cols_keep = ['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'Parch', 'Pclass', 'Embarked', '2urvived']

Now apply and rename

In [6]:
df = df_raw[cols_keep].rename(columns={'2urvived':'Survived','sibsp':'SibSp'})

Lets check our changes

In [7]:
df.head(10)

   Passengerid   Age     Fare  Sex  SibSp  Parch  Pclass  Embarked  Survived
0            1  22.0   7.2500    0      1      0       3       2.0         0
1            2  38.0  71.2833    1      1      0       1       0.0         1
2            3  26.0   7.9250    1      0      0       3       2.0         1
3            4  35.0  53.1000    1      1      0       1       2.0         1
4            5  35.0   8.0500    0      0      0       3       2.0         0
5            6  28.0   8.4583    0      0      0       3       1.0         0
6            7  54.0  51.8625    0      0      0       1       2.0         0
7            8   2.0  21.0750    0      3      1       3       2.0         0
8            9  27.0  11.1333    1      0      2       3       2.0         1
9           10  14.0  30.0708    1      1      0       2       0.0         1

To know shape and data types we can simply use df.shape and df.types

In [8]:
print("Shape of the DataFrame:", df.shape)

Shape of the DataFrame: (100, 9)

In [9]:
print("Data frame types: ", df.dtypes)

Data frame types:  Passengerid      int64
Age            float64
Fare           float64
Sex              int64
SibSp            int64
Parch            int64
Pclass           int64
Embarked       float64
Survived         int64
dtype: object

Now lets change some our data for our convinience

In [10]:
#lets make Pclass as categorical variable
df['Pclass'] = df['Pclass'].astype('category')

Aslo we can make sex as a numerical

In [11]:
df['Sex_label'] = df['Sex'].map({0: "male", 1: "female"})

And lets check

In [12]:
print(df.dtypes)

Passengerid       int64
Age             float64
Fare            float64
Sex               int64
SibSp             int64
Parch             int64
Pclass         category
Embarked        float64
Survived          int64
Sex_label        object
dtype: object

Sex_label NOW object!

We can also print only key parametrs if they can be asked

In [13]:
params = [
    'sep',
    'encoding',
    'usecols',
    'dtype',
    'parse_dates',
    'na_values',
    'index_col',
    'nrows',
    'skiprows',
    'header'
]

print("Parameters used in pd.read_csv():")
print(params)

Parameters used in pd.read_csv():
['sep', 'encoding', 'usecols', 'dtype', 'parse_dates', 'na_values', 'index_col', 'nrows', 'skiprows', 'header']

## 2.Data set inspection

All that you must do with a new DATA set!

In [14]:
display(df.head()) #gonna print first 5 rows

,Passengerid,Age,Fare,Sex,SibSp,Parch,Pclass,Embarked,Survived,Sex_label
0,1,22.0,7.2500,0,1,0,3,2.0,0,male
1,2,38.0,71.2833,1,1,0,1,0.0,1,female
2,3,26.0,7.9250,1,0,0,3,2.0,1,female
3,4,35.0,53.1000,1,1,0,1,2.0,1,female
4,5,35.0,8.0500,0,0,0,3,2.0,0,male

In [15]:
display(df.tail()) #gonna print last 5 rows

,Passengerid,Age,Fare,Sex,SibSp,Parch,Pclass,Embarked,Survived,Sex_label
95,96,28.0,8.0500,0,0,0,3,2.0,0,male
96,97,71.0,34.6542,0,0,0,1,0.0,0,male
97,98,23.0,63.3583,0,0,1,1,0.0,1,male
98,99,34.0,23.0000,1,0,1,2,2.0,1,female
99,100,34.0,26.0000,0,1,0,2,2.0,0,male

In [16]:
print("Shape:", df.shape) #columns and rows

Shape: (100, 10)

In [17]:
#Also df.info() can be used to get a concise summary of the DataFrame, including the number of non-null entries and data types for each column.


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  100 non-null    int64
 1   Age          100 non-null    float64
 2   Fare         100 non-null    float64
 3   Sex          100 non-null    int64
 4   SibSp        100 non-null    int64
 5   Parch        100 non-null    int64
 6   Pclass       100 non-null    category
 7   Embarked     99 non-null     float64
 8   Survived     100 non-null    int64
 9   Sex_label    100 non-null    object
dtypes: category(1), float64(3), int64(5), object(1)
memory usage: 7.4+ KB

In [18]:
#df.describe() can be used to generate descriptive statistics of the DataFrame, including count, mean, standard deviation, minimum, maximum, and quartiles for each numeric column.

display(df.describe())

,Passengerid,Age,Fare,Sex,SibSp,Parch,Embarked,Survived
count,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,99.000000,100.000000
mean,50.500000,27.58330,29.517625,0.390000,0.730000,0.440000,1.484848,0.410000
std,29.011492,13.47654,40.972905,0.490207,1.179411,0.967346,0.825161,0.494311
min,1.000000,0.83000,7.225000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25.750000,20.75000,8.050000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,50.500000,28.00000,15.675000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,75.250000,32.00000,32.134375,1.000000,1.000000,0.000000,2.000000,1.000000
max,100.000000,71.00000,263.000000,1.000000,5.000000,5.000000,2.000000,1.000000

Now lets check how we can count values

In [19]:
#value_check how many unique values are there in each column

print("Unique values for each Pclass:" )

print(df['Pclass'].value_counts())

Unique values for each Pclass:
Pclass
3    61
1    21
2    18
Name: count, dtype: int64

Lets used normalize=True, instead of a quantity, it gives fractions (0.0–1.0); multiplying by 100 gives the percentage

In [20]:
print('Survival rate (%):')
print((df['Survived'].value_counts(normalize=True) * 100).round(2))

Survival rate (%):
Survived
0    59.0
1    41.0
Name: proportion, dtype: float64

In [21]:
#if we work with cathegorical data, we can use just describe()

print("Categorical data description:")
print(df[['Sex_label','Pclass']].describe())

Categorical data description:
       Sex_label  Pclass
count        100     100
unique         2       3
top         male       3
freq          61      61

## 3. loc \ iloc \ boolean mask

`iloc` is used to select data by numerical position (row/column index) rather than by label.

In [22]:
print('---iloc---')
print(df.iloc[0]) #first row

---iloc---
Passengerid       1
Age            22.0
Fare           7.25
Sex               0
SibSp             1
Parch             0
Pclass            3
Embarked        2.0
Survived          0
Sex_label      male
Name: 0, dtype: object

In [23]:
print(df.iloc[-1])           # last row

Passengerid     100
Age            34.0
Fare           26.0
Sex               0
SibSp             1
Parch             0
Pclass            2
Embarked        2.0
Survived          0
Sex_label      male
Name: 99, dtype: object

In [24]:
#at the same time u can print multiple rows and columns using iloc

print(df.iloc[0:3,1:4]) #first 3 rows and columns from 1 to 3

    Age     Fare  Sex
0  22.0   7.2500    0
1  38.0  71.2833    1
2  26.0   7.9250    1

`loc` at the same time works not with positions,works with labels

In [25]:
print('--- loc ---')
print(df.loc[0,'Age']) #first row using loc and column name 'Age'

--- loc ---
22.0

In [26]:
print(df.loc[0:4, ['Age', 'Fare']])  #raws from 0 to 4 and columns 'Age' and 'Fare'
print()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [27]:
# MAIN DIFFERENCE:
# df.loc[0:4]  → 5 rows (0,1,2,3,4) — right border do not include
# df.iloc[0:4] → 4 rows (0,1,2,3)  — right border include

Here u can see!

In [28]:
print('loc[0:4] rows:', len(df.loc[0:4]))

loc[0:4] rows: 5

In [29]:
print('iloc[0:4] rows:', len(df.iloc[0:4]))

iloc[0:4] rows: 4

'Boolean mask' the most popular filtration mechanism

In [30]:
mask_female = df['Sex'] == 1
mask_survived = df['Survived'] == 1
mask_rich = df['Fare'] > 100
#now it is our conditions!
#it returns true or false for each row in the DataFrame based on whether the condition is met or not. We can use these masks to filter the DataFrame and select only the rows that meet certain criteria.

In [31]:
#now we can use these masks to filter the DataFrame and select only the rows that meet certain criteria. For example, we can use

df_vip_women = df[mask_female & mask_survived & mask_rich]
print("Wealthy women who survived:")
print(len(df_vip_women))

Wealthy women who survived:
2

There are also other options like `query` and `isin()`

In [32]:
df_q = df.query('Sex == 1 and Survived == 1 and Fare > 100')
print("Wealthy female survivors with high fares:", df_q.shape[0])

Wealthy female survivors with high fares: 2

In [33]:
df_isin = df[df['Pclass'].isin([1, 2])]
print("Passengers in Pclass 1 or 2:", df_isin.shape[0])

Passengers in Pclass 1 or 2: 39

We can also use loc for editing , select rows based on a condition and edit the values in the relevant column straight away

WORK WITH COPY!

`df_copy = df.copy()`

In [34]:
df_copy = df.copy() 

df_copy.loc[df_copy['Age'] < 1, 'Age'] = 0
print("Passengers with age 0:", df_copy[df_copy['Age'] == 0].shape[0])

Passengers with age 0: 1

In [35]:
#create new column 

df_copy['Note'] = None

df_copy['Note'] = None
df_copy.loc[df_copy['Fare'] > 100, 'Note'] = 'VIP'
df_copy.loc[df_copy['Fare'] <= 100, 'Note'] = 'Regular'

print("Passengers with VIP note:", (df_copy['Note']=='VIP').sum())

Passengers with VIP note: 3

In [36]:
df_copy.head(5)

,Passengerid,Age,Fare,Sex,SibSp,Parch,Pclass,Embarked,Survived,Sex_label,Note
0,1,22.0,7.2500,0,1,0,3,2.0,0,male,Regular
1,2,38.0,71.2833,1,1,0,1,0.0,1,female,Regular
2,3,26.0,7.9250,1,0,0,3,2.0,1,female,Regular
3,4,35.0,53.1000,1,1,0,1,2.0,1,female,Regular
4,5,35.0,8.0500,0,0,0,3,2.0,0,male,Regular

## 4.Cleaning data

In [37]:
# --- isnull / notnull ---
print('Missing values:')

missing_values = df.isnull().sum() #how many missing values in each column

pct = (df.isnull().sum() / len(df) * 100).round(2)

print(missing_values)
print(pct)

Missing values:
Passengerid    0
Age            0
Fare           0
Sex            0
SibSp          0
Parch          0
Pclass         0
Embarked       1
Survived       0
Sex_label      0
dtype: int64
Passengerid    0.0
Age            0.0
Fare           0.0
Sex            0.0
SibSp          0.0
Parch          0.0
Pclass         0.0
Embarked       1.0
Survived       0.0
Sex_label      0.0
dtype: float64

In [38]:
display(pd.DataFrame({'count': missing_values, 'pct_%': pct})[missing_values > 0])

          count  pct_%
Embarked      1    1.0

In [39]:
print('Raws at least one missing value:', df.isnull().any(axis=1).sum())
print('Fully filled rows:', df.notna().all(axis=1).sum())

Raws at least one missing value: 1
Fully filled rows: 99

SO we need to have some stratages to fill missing values

In [40]:
df_clean = df.copy()

#we can use Konstant,so fill Nan with fix value like 0,"unknown" or "missing" or we can use mean, median, mode to fill missing values. It depends on the data and the context of the analysis.


#Konstant

df_clean["Embarked"] = df_clean["Embarked"].fillna(0)

#Or median,more better with jumps
#df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())


#Best practice is median inside group

df_clean['Age'] = df_clean.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.median()))


#also when data is sorted by some column, we can use ffill or bfill to fill missing values based on the previous or next value in the column. This is useful when the data is sorted by time or some other variable that has a natural order.

# df_clean['value'] = df_clean['value'].ffill()   #next value
# df_clean['value'] = df_clean['value'].bfill()   #previous value

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\1549480101.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean['Age'] = df_clean.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.median()))

In [41]:
print("Missing values after cleaning:")
print()
print(df_clean.isnull().sum())

Missing values after cleaning:

Passengerid    0
Age            0
Fare           0
Sex            0
SibSp          0
Parch          0
Pclass         0
Embarked       0
Survived       0
Sex_label      0
dtype: int64

There is also method like `dropna`.It just delete all gaps with missing values


But in practise better to use fillna

In [42]:
print('Original:', df.shape)

print('dropna(any):', df.dropna(how='any').shape)
print('dropna(subset=[Embarked]):', df.dropna(subset=['Embarked']).shape)
print('dropna(thresh=8):', df.dropna(thresh=8).shape)

Original: (100, 10)
dropna(any): (99, 10)
dropna(subset=[Embarked]): (99, 10)
dropna(thresh=8): (100, 10)

`duplicated()` , returns a Boolean value, where True indicates that the string is a duplicate. 

`drop_dublicates` - delete them

In [43]:
print("dublicates:", df.duplicated().sum())

print('Dublicates in PassengerId:', df.duplicated(subset=['Passengerid']).sum())


df_dedup = df.drop_duplicates(subset=['Passengerid'], keep='first') 
#keep first means that we keep the first occurrence of the duplicate and drop the rest. We can also use keep='last' to keep the last occurrence or keep=False to drop all duplicates.


#wse also can keep='last' and keep="False"
print('Shape after dropping duplicates:', df_dedup.shape)

dublicates: 0
Dublicates in PassengerId: 0
Shape after dropping duplicates: (100, 10)

The IQR method is the standard way of identifying outliers.

we take the ‘normal range’ of data, and anything that falls significantly outside it is discarded.

In [44]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1

print("IQR:", IQR)

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR


outliers = df[(df['Fare'] < lower) | (df['Fare'] > upper)] 

print(f'IQR range: [{lower:.1f}, {upper:.1f}]')
print(f'Outliers Fare: {len(outliers)} rowas ({len(outliers)/len(df)*100:.1f}%)')
print(f'Max Fare in data: {df["Fare"].max():.0f}')

IQR: 24.084374999999998
IQR range: [-28.1, 68.3]
Outliers Fare: 9 rowas (9.0%)
Max Fare in data: 263

Later we can decide what to do with it,maybe leave,maybe replace with upper

or just leave it like that,depends on possible tasks

## 5.GROUPBY

`groupby`  splits the DataFrame into groups and applies an aggregation function to each one.

In [45]:
print("Survival rate by Pclass:")

print(df.groupby('Pclass')['Survived'].mean().round(2))
print()

Survival rate by Pclass:
Pclass
1    0.48
2    0.67
3    0.31
Name: Survived, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\3416278290.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('Pclass')['Survived'].mean().round(2))

In [46]:
df.Age.describe()

count    100.00000
mean      27.58330
std       13.47654
min        0.83000
25%       20.75000
50%       28.00000
75%       32.00000
max       71.00000
Name: Age, dtype: float64

In [47]:
print("Survival rate by age group:")
df.groupby(pd.cut(df["Age"], bins=[0,12,18,35,60,100]))['Survived'].mean().round(2)

Survival rate by age group:

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\1591519753.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df["Age"], bins=[0,12,18,35,60,100]))['Survived'].mean().round(2)

Age
(0, 12]      0.40
(12, 18]     0.50
(18, 35]     0.41
(35, 60]     0.43
(60, 100]    0.00
Name: Survived, dtype: float64

In [48]:
print('Age and Fare by sex:')

print(df.groupby('Sex_label')[['Age', 'Fare']].mean().round(2))

Age and Fare by sex:
             Age   Fare
Sex_label
female     25.92  31.85
male       28.64  28.03

In [49]:
# --- agg: gives us the aggregated values ---


result = df.groupby('Pclass').agg(
    count=('Passengerid', 'count'),
    survival_rate=('Survived', 'mean'),
    avg_age=('Age', 'mean'),
    avg_fare=('Fare', 'mean'),
    max_fare=('Fare', 'max'),
    min_fare=('Fare', 'min')
).round(2)


display(result)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\592278831.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby('Pclass').agg(

        count  survival_rate  avg_age  avg_fare  max_fare  min_fare
Pclass
1          21           0.48    38.76     78.30     263.0     26.55
2          18           0.67    26.94     23.24      73.5     10.50
3          61           0.31    23.93     14.57      56.5      7.22

In [50]:
Sex_label = df.groupby("Sex").agg(
    count=('Passengerid', 'count'),
    survival_rate=('Survived', 'mean'),
    avg_age = ('Age', 'mean'),
    avg_fare = ('Fare', 'mean'),
    min_age = ('Age', 'min'),
    max_age = ('Age', 'max')

)

display(Sex_label)

     count  survival_rate    avg_age   avg_fare  min_age  max_age
Sex
0       61       0.163934  28.644754  28.026843     0.83     71.0
1       39       0.794872  25.923077  31.849362     3.00     58.0

In [51]:
Embarked_check = df.groupby("Embarked").agg(
    count=('Passengerid', 'count'),
    survival_rate=('Survived', 'mean'),
    avg_fare = ('Fare', 'mean'),
    mean_fare = ('Fare', 'mean'),

    max_class = ('Pclass', lambda x: x.mode()[0])
).round(2)

display(Embarked_check)

          count  survival_rate  avg_fare  mean_fare max_class
Embarked
0.0          21           0.48     36.69      36.69         3
1.0           9           0.67     11.13      11.13         3
2.0          69           0.35     29.00      29.00         3

In [52]:
# we can also group by multiple columns and apply different aggregation functions to each column. For example, we can group by both 'Pclass' and

result2 = (
    df.groupby(['Pclass', 'Sex_label'])['Survived']
    .agg(['mean', 'count'])
    .rename(columns={'mean': 'survival_rate', 'count': 'num_passengers'})
    .round(3)
    .sort_values('survival_rate', ascending=False)
    .reset_index()
)

display(result2)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\4127163724.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Pclass', 'Sex_label'])['Survived']

  Pclass Sex_label  survival_rate  num_passengers
0      1    female          1.000               7
1      2    female          0.900              10
2      3    female          0.682              22
3      2      male          0.375               8
4      1      male          0.214              14
5      3      male          0.103              39

In [53]:
embarked_map = {0.0: 'S', 1.0: 'C', 2.0: 'Q'}
df['Embarked'] = df['Embarked'].map(embarked_map)

In [54]:
result3 = (
    df.groupby(['Pclass','Embarked'])["Fare"]
    .agg(['mean','median', 'count'])
    .rename(columns={'mean': 'avg_fare', 'median': 'med_fare', 'count': 'num_passengers'})
    .sort_values('avg_fare', ascending=False)
    .round(2)
)

display(result3)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\4248801142.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Pclass','Embarked'])["Fare"]

                 avg_fare  med_fare  num_passengers
Pclass Embarked
1      Q            88.39     52.00              11
       S            65.79     63.36               9
2      S            35.83     35.83               2
       Q            21.67     18.50              16
3      Q            16.24      8.83              42
       C            11.13      7.88               9
       S            10.67      7.56              10
1      C              NaN       NaN               0
2      C              NaN       NaN               0

In [55]:
df['Fare_median_by_class'] = df.groupby('Pclass')['Fare'].transform('median')
df['Fare_vs_class_median'] = df['Fare'] - df['Fare_median_by_class']

print('Fare vs class median:')
display(df[['Pclass', 'Fare', 'Fare_median_by_class', 'Fare_vs_class_median']].head(8))

Fare vs class median:

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\3620011136.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['Fare_median_by_class'] = df.groupby('Pclass')['Fare'].transform('median')

  Pclass     Fare  Fare_median_by_class  Fare_vs_class_median
0      3   7.2500                 8.050               -0.8000
1      1  71.2833                61.175               10.1083
2      3   7.9250                 8.050               -0.1250
3      1  53.1000                61.175               -8.0750
4      3   8.0500                 8.050                0.0000
5      3   8.4583                 8.050                0.4083
6      1  51.8625                61.175               -9.3125
7      3  21.0750                 8.050               13.0250

## 6. merge / join/

In [56]:
passengers = df[['Passengerid', 'Age', 'Survived', 'Pclass']].head(10).copy()

class_info = pd.DataFrame({
    'Pclass': [1, 2, 3],
    'Description': ['Upper class', 'Middle class', 'Lower class'],
    "avg_ticket_price": [100, 50, 25]
})

#inner join - only rowa with matching Pclass values in both DataFrames

merged = passengers.merge(class_info, on='Pclass', how='inner')
print('Inner join:', merged.shape)
display(merged.head())

Inner join: (10, 6)

   Passengerid   Age  Survived  Pclass  Description  avg_ticket_price
0            1  22.0         0       3  Lower class                25
1            2  38.0         1       1  Upper class               100
2            3  26.0         1       3  Lower class                25
3            4  35.0         1       1  Upper class               100
4            5  35.0         0       3  Lower class                25

In [57]:
# LEFT JOIN — all rows from the left DataFrame (passengers) are included in the result, and matching rows from the right DataFrame (class_info) are included where available. If there is no match, the result will contain NaN for the columns from the right DataFrame.
cabin_data = pd.DataFrame({
    'Passengerid': [1, 2, 3],
    'cabin': ['C85', 'E46', None]
})

merged_left = passengers.merge(cabin_data, on='Passengerid', how='left')
print('Left join (all 10 passengers):', merged_left.shape)
display(merged_left)

Left join (all 10 passengers): (10, 5)

   Passengerid   Age  Survived Pclass cabin
0            1  22.0         0      3   C85
1            2  38.0         1      1   E46
2            3  26.0         1      3  None
3            4  35.0         1      1   NaN
4            5  35.0         0      3   NaN
5            6  28.0         0      3   NaN
6            7  54.0         0      1   NaN
7            8   2.0         0      3   NaN
8            9  27.0         1      3   NaN
9           10  14.0         1      2   NaN

In [58]:
df_a = pd.DataFrame({'id': [1, 2, 3],           'val_a': ['x', 'y', 'z']})
df_b = pd.DataFrame({'passenger_id': [1, 2, 4], 'val_b': ['a', 'b', 'c']})

merged_keys = df_a.merge(df_b, left_on='id', right_on='passenger_id', how='outer')
display(merged_keys)



print('\nTypes of join: inner | left | right | outer (analogues SQL JOIN)')

    id val_a  passenger_id val_b
0  1.0     x           1.0     a
1  2.0     y           2.0     b
2  3.0     z           NaN   NaN
3  NaN   NaN           4.0     c

Types of join: inner | left | right | outer (analogues SQL JOIN)

In [59]:
df_part1 = df.iloc[:500]
df_part2 = df.iloc[500:]

df_concat = pd.concat([df_part1, df_part2], ignore_index=True)
print('Concat :', df_concat.shape)

Concat : (100, 12)

## 7. pivot_table

`groupby` would produce a list of rows, whereas `pivot_table` produces a cross-tabulation table , which is easier to read when you need to compare two variables at the same time.

In [60]:
pt = pd.pivot_table(
    df,
    values  = 'Survived',
    index   = 'Pclass',
    columns = 'Sex_label',
    aggfunc = 'mean',
    margins = True,   # строка/колонка итогов 'All'
).round(3)

print('Survival rate по Pclass x Sex:')
display(pt)

Survival rate по Pclass x Sex:

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\2255994572.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pt = pd.pivot_table(

Sex_label  female   male    All
Pclass
1           1.000  0.214  0.476
2           0.900  0.375  0.667
3           0.682  0.103  0.311
All         0.795  0.164  0.410

In [62]:
pt2 = pd.pivot_table(
    df,
    values  = ['Age', 'Fare'],
    index   = 'Pclass',
    columns = 'Sex_label',
    aggfunc = {'Age': 'mean', 'Fare': 'median'},
).round(2)

display(pt2)


pt2_flat = pt2.stack(level=1).reset_index()
print('\n After stack + reset_index:')
display(pt2_flat.head())

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\3902226431.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pt2 = pd.pivot_table(

             Age          Fare
Sex_label female   male female   male
Pclass
1          38.43  38.93  76.73  51.93
2          23.40  31.35  22.00  19.50
3          23.09  24.40  10.30   8.05

 After stack + reset_index:

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\3902226431.py:12: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pt2_flat = pt2.stack(level=1).reset_index()

  Pclass Sex_label    Age   Fare
0      1    female  38.43  76.73
1      1      male  38.93  51.93
2      2    female  23.40  22.00
3      2      male  31.35  19.50
4      3    female  23.09  10.30

## 8.Map, Apply, Assign

`map` replaces each value in a column according to a dictionary.

In [63]:
df['Pclass_name'] = df['Pclass'].map({1: 'First', 2: 'Second', 3: 'Third'})
print(df[['Pclass', 'Pclass_name']].value_counts().sort_index())

Pclass  Pclass_name
1       First          21
2       Second         18
3       Third          61
Name: count, dtype: int64

`apply`  applies the function to each element/string

In [65]:
df['FamilySize_fast'] = df['SibSp'] + df['Parch'] + 1

# np.where - if/else
df['IsAlone'] = np.where(df['FamilySize_fast'] == 1, 1, 0)

# pd.cut - cut to bins with labels
df['Fare_bin'] = pd.cut(
    df['Fare'],
    bins=[0, 10, 30, 100, 1000],
    labels=['low', 'mid', 'high', 'vip']
)

# pd.qcut - cut to quantiles
df['Age_quartile'] = pd.qcut(df['Age'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

display(df[['Fare', 'Fare_bin', 'Age', 'Age_quartile', 'IsAlone']].head(8))

      Fare Fare_bin   Age Age_quartile  IsAlone
0   7.2500      low  22.0           Q2        0
1  71.2833     high  38.0           Q4        0
2   7.9250      low  26.0           Q2        1
3  53.1000     high  35.0           Q4        0
4   8.0500      low  35.0           Q4        1
5   8.4583      low  28.0           Q2        1
6  51.8625     high  54.0           Q4        1
7  21.0750      mid   2.0           Q1        0

`assign` , adds new columns without modifying the original `df`, and returns a new one.
Within `assign`, `x` refers to the current DataFrame at this stage of the pipeline. Each column is computed using the lambda expression `x`

In [66]:
df_features = (
    df[['Passengerid', 'Age', 'Fare', 'SibSp', 'Parch', 'Sex', 'Pclass', 'Survived']]
    .assign(
        FamilySize   = lambda x: x['SibSp'] + x['Parch'] + 1,
        IsAlone      = lambda x: (x['SibSp'] + x['Parch'] == 0).astype(int),
        FarePerPerson= lambda x: (x['Fare'] / x['FamilySize']).round(2),
        AgeGroup     = lambda x: pd.cut(
            x['Age'], bins=[0, 18, 60, 100], labels=['child', 'adult', 'senior']
        ),
    )
    .dropna(subset=['AgeGroup'])
    .reset_index(drop=True)
)

display(df_features.head())
print('Shape:', df_features.shape)

,Passengerid,Age,Fare,SibSp,Parch,Sex,Pclass,Survived,FamilySize,IsAlone,FarePerPerson,AgeGroup
0,1,22.0,7.2500,1,0,0,3,0,2,0,3.62,adult
1,2,38.0,71.2833,1,0,1,1,1,2,0,35.64,adult
2,3,26.0,7.9250,0,0,1,3,1,1,1,7.92,adult
3,4,35.0,53.1000,1,0,1,1,1,2,0,26.55,adult
4,5,35.0,8.0500,0,0,0,3,0,1,1,8.05,adult

Shape: (100, 12)

In [67]:

result = (
    df
    .query('Age > 0')                           #filter
    .assign(
        FamilySize = lambda x: x['SibSp'] + x['Parch'] + 1,
        IsAlone    = lambda x: (x['SibSp'] + x['Parch'] == 0).astype(int),
    )
    .groupby(['Pclass', 'Sex_label'])
    .agg(
        n              = ('Passengerid', 'count'),
        survival_rate  = ('Survived', 'mean'),
        pct_alone      = ('IsAlone', 'mean'),
        avg_family     = ('FamilySize', 'mean'),
    )
    .round(3)
    .sort_values('survival_rate', ascending=False)
    .reset_index()
)

display(result)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21320\3826106621.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['Pclass', 'Sex_label'])

  Pclass Sex_label   n  survival_rate  pct_alone  avg_family
0      1    female   7          1.000      0.286       2.286
1      2    female  10          0.900      0.400       2.000
2      3    female  22          0.682      0.455       2.636
3      2      male   8          0.375      0.750       1.375
4      1      male  14          0.214      0.500       1.786
5      3      male  39          0.103      0.641       2.231

In [69]:

from random import sample

sample = pd.Series(['  Jack Dawson  ', 'Rose DeWitt  ', 'Cal HOCKLEY', 'mr. Andrews'])



print(sample.str.strip())                            #delete spaces from the edges
print(sample.str.lower())                            # lower case
print(sample.str.title())                            # title case
print(sample.str.contains('Dawson', na=False))       # True/False
print(sample.str.replace(r'\s+', ' ', regex=True))  # remove double spaces
print(sample.str.split(' ', expand=True))            # split into DataFrame

0    Jack Dawson
1    Rose DeWitt
2    Cal HOCKLEY
3    mr. Andrews
dtype: object
0      jack dawson
1      rose dewitt
2        cal hockley
3        mr. andrews
dtype: object
0      Jack Dawson
1      Rose Dewitt
2        Cal Hockley
3        Mr. Andrews
dtype: object
0     True
1    False
2    False
3    False
dtype: bool
0     Jack Dawson
1     Rose DeWitt
2      Cal HOCKLEY
3      mr. Andrews
dtype: object
      0        1     2       3     4     5
0                 Jack  Dawson
1  Rose   DeWitt                None  None
2   Cal  HOCKLEY  None    None  None  None
3   mr.  Andrews  None    None  None  None